# Generated by Django 5.0.6 on 2024-06-07 05:47

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_type', models.CharField(choices=[('Single Room', 'Single Room'), ('Family Room', 'Family Room'), ('Presidential Room', 'Presidential Room')], max_length=50)),
                ('room_number', models.CharField(max_length=10, unique=True)),
                ('capacity', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Room_image', models.ImageField(default='default_room_image.jpg', upload_to='photos/Rooms')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_of_rooms', models.IntegerField(default=0)),
                ('check_in_date', models.DateField()),
                ('check_in_time', models.TimeField(default=datetime.time(0, 0))),
                ('check_out_date', models.DateField()),
                ('is_checked_out', models.BooleanField(default=False)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APP.room')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('age', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=50)),
                ('Email', models.CharField(max_length=50)),
                ('proof', models.ImageField(upload_to='photos/user')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APP.ticket')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APP.users')),
            ],
        ),
    ]
